site_name: VisionsTrust Documentation
site_description: Documentation for VisionsTrust Application & API
site_author: Visions
docs_dir: docs
site_dir: ./site
site_url: https://docs/visionstrust.com
repo_url: https://github.com/VisionsOfficial/visionstrust-docs
edit_uri: blob/main/docs/
copyright: Visions 2024
plugins:
  - search
  - mermaid2
markdown_extensions:
  - attr_list
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - search.highlight
    - search.share

nav: 
  - Home: index.md
  - Glossary: glossary.md
  - Application:
    - Getting Started:
      - Overview: application/overview.md
      - Onboarding: application/onboarding.md
      - Dashboard: application/dashboard.md
    - Discovery: 
      - Browsing: application/discovery/index.md
      - Offers: application/discovery/offers.md
      - Projects: application/discovery/projects.md
    - Offers:
      - Overview: application/registering-resources/overview.md
      - Creating an offer: application/registering-resources/creating-an-offer.md
      - Data Resource: application/registering-resources/data-resources.md
      - Service Resource: application/registering-resources/service-resources.md
    - Projects:
      - Overview: application/projects/overview.md
      - Creating a Project: application/projects/creating-a-project.md
      - Project Settings: application/projects/project-settings.md
    - Negotiation:
      - Peer-to-Peer: application/negotiation/peer-to-peer.md
      - Project:
        - Project Negotiation: application/negotiation/project-negotiation.md
        - Invitations: application/negotiation/invitations.md
        - Join Requests: application/negotiation/join-requests.md
        - Negotiation Process: application/negotiation/negotiation.md
  - Developers:
    - Requirements: guide/requirements.md
    - Setting up a connector: guide/setting-up-a-connector.md
    - Setting up resources: guide/setting-up-technical-resources.md
    - Integrating consent: guide/setting-up-for-consent.md
    - API Consumption: guide/api-consumption-flow.md
    - Testing: guide/testing.md